name: "Auto Request Reviews"
description: "Automatically requests reviews from members of a specified team"

inputs:
  reviewers:
    description: "Desired total number of reviewers in total"
    required: true
  team:
    description: "Team to pick reviewers from (format: org/team)"
    required: true
  token:
    description: "GitHub token with permissions to request reviews"
    required: true
  debug:
    description: "Enable debug mode (for local testing only)"
    required: false
    default: "false"
  repo:
    description: "Repository name in format 'owner/repo' (only used in debug mode)"
    required: false
  pr_number:
    description: "Pull request number (only used in debug mode)"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
